version: "3.8"

services:
  simple-chat-app:
    build: .
    container_name: simple-chat-app
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - chat_network

  nginx:
    image: nginx:alpine
    container_name: simple-chat-nginx
    ports:
      - "8094:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simple-chat-app
    restart: unless-stopped
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
