version: "3.8"

services:
  simple-chat-app:
    build: .
    container_name: simple-chat-app
    ports:
      - "8094:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    driver: bridge
